Layout/EndOfLine:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false